### ISSUE TITLE
Contribute german translation

### ISSUE THREAD

**Issue by rmeissn** [Unrud/video-downloader#10]
Hey there,

I'm not really experienced with Python and GTK development, but would be happy to contribute a german translation of your programs texts. I've already spotted a PO folder, but haven't seen any language files yet.

Furthermore I recommend to add a few more words to the dialogs of your program. Gydl is a similar program and its dialogs are are good examples: https://github.com/JannikHv/gydl#usage

**Comment by Unrud** [comment]
> I've already spotted a PO folder, but haven't seen any language files yet.

The applications is translateable. To generate the POT file run something like:

```
meson . _build
ninja -C _build video-downloader-pot
```

The generated file can be found at `po/video-downloader.pot`. Create the german translation at `po/de.po` and append the line `de` to the file `po/LINGUAS`.

> Furthermore I recommend to add a few more words to the dialogs of your program.

Please be more specific.

**Comment by rmeissn** [comment]
These dialogs are included in the mentioned application and are more specific than your current ones. I think such dialogs would ease the program even more for unexperienced users.

![image](https://user-images.githubusercontent.com/855967/79967429-1d00c180-848f-11ea-97bb-370bb20f6c16.png)
![image](https://user-images.githubusercontent.com/855967/79967490-3275eb80-848f-11ea-876a-154087914785.png)
![image](https://user-images.githubusercontent.com/855967/79967513-373a9f80-848f-11ea-8d47-f8dadc4b4698.png)
