### ISSUE TITLE
Port from GTK 3 to GTK 4

### ISSUE THREAD

**Issue by vanillajonathan** [Unrud/video-downloader#102]
https://developer.gnome.org/hig/
https://docs.gtk.org/gtk4/migrating-3to4.html

**Comment by nonetrix** [comment]
Has this improved since Ubuntu ships the current version of GNOME?

**Comment by TheOPtimal** [comment]
I feel like dropping Snap is the best outcome here. It's not a great option, but Snap really only works well on Ubuntu and even there users are encouraged to use Flatpak, which most distros use and which generally also works a lot better. Even GNOME Software has dropped support for it.

**Comment by nonetrix** [comment]
Could just keep it at a older version temporarily I guess

**Comment by Unrud** [comment]
> I feel like dropping Snap is the best outcome here.

You are probably right. I tried upgrading core18 to core20 and Snapcraft is still a buggy mess. I've already invested too much time in it and I'm not willing to deal with it anymore.

**Comment by vanillajonathan** [comment]
There is now `core22`.
https://snapcraft.io/core22

**Comment by Unrud** [comment]
> There is now `core22`.

Yes, but the Gnome extension is for `core20`.
