### ISSUE TITLE
not recoding working just an error message 

### ISSUE THREAD

**Issue by poperpoper** [Unrud/video-downloader#11]
will not record like it did a few weeks ago just gives error message about a play-list issue ? ill bet and update on Yt lands part messed it up who know i make classic car run better n look betteer n stuff not code

**Comment by Unrud** [comment]
Can you provide the URL of the playlist that is not working?

**Comment by Unrud** [comment]
Please check if the problem still exists in version 0.2.8 and provide an example URL or at least the error message.
I close this issue for now.
