### ISSUE TITLE
Ability to download age-restricted Youtube videos

### ISSUE THREAD

**Issue by guiguidu60** [Unrud/video-downloader#114]
Some Youtube videos require authentication in order to be viewed: this also applies when you want to download it.
Suddenly, when a person wants to download such a video on the application, it asks us for authentication but it does not work because it is only in the case of private videos.
It would therefore be necessary to add support for logging into our Google account to obtain the necessary authentication to be able to download videos whose access is restricted because of age.

**Comment by Unrud** [comment]
It's an issue with [youtube-dl](https://github.com/ytdl-org/youtube-dl) for a long time. Maybe we should switch to a more active fork like [yt-dlp](https://github.com/yt-dlp/yt-dlp).

**Comment by gregorydk** [comment]
youtube-dl is very slow for YouTube. Switching to yt-dlp would fix that.

**Comment by Unrud** [comment]
Switched to yt-dlp. At least some age-restricted videos work now.

**Comment by guiguidu60** [comment]
> Switched to yt-dlp. At least some age-restricted videos work now.

It works ! Thank you :D
