### ISSUE TITLE
Playing video's with GNOME Videos (Totem) gives x-subtitle-unknown decoder

### ISSUE THREAD

**Issue by Eonfge** [Unrud/video-downloader#124]
I discovered an issue when trying to play a video with auto-generated subtitles. The user gets an `x-subtitle-unknown decoder` and the user is then told to go to the software center do download the right codec.

The problem then comes up, what codec? What extension or library do I need to play the bundled subtitles?

![Screenshot from 2022-01-31 09-29-37](https://user-images.githubusercontent.com/33983090/151761559-8f197679-0e33-4b34-b0e7-4df7c66d4d6f.png)

_If I understand the problem better, I can also make an upstream-issue so that Totem can fix the issue. It's possible that this is an issue with the GStreamer framework, but I first want to understand the issue better._

**Comment by Unrud** [comment]
I've opened an issue: https://gitlab.gnome.org/GNOME/totem/-/issues/511
