### ISSUE TITLE
Allow video-downloader to be run with `%s` argument

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#13]
Hi,

Thanks for this application !

I'd like to run video-downloader with `%s` argument but it doesn't seem to work.

I tried to run `flatpak run com.github.unrud.VideoDownloader https://www.youtube.com/watch?v=qAjPRr5SGoY` for instance, but I got `(video-downloader:3): GLib-GIO-CRITICAL **: 01:39:47.560: This application can not open files.`

here is one use case : I use the Open With addon for Firefox which allows to pass current URL to any application using the usual  `%s` argument

Thanks !

**Comment by antistress** [comment]
Hi,
Seing that you closed this bug with a commit, I was pretty excited to try com.github.unrud.VideoDownloader 0.2.7
But running `$ flatpak run com.github.unrud.VideoDownloader https://www.youtube.com/watch?v=qAjPRr5SGoY` lead to `(video-downloader:3): GLib-GIO-CRITICAL **: 04:39:12.984: This application can not open files.`
Did I miss something ?
Thanks !

**Comment by Unrud** [comment]
```
flatpak run com.github.unrud.VideoDownloader --url https://www.youtube.com/watch?v=qAjPRr5SGoY
```

**Comment by antistress** [comment]
That's great !
Thanks for the application, and for taking this request for enhancement into account :)
