### ISSUE TITLE
Add DRM protected video support

### ISSUE THREAD

**Issue by pervoj** [Unrud/video-downloader#133]
The app is really good for downloading videos from the Czech Television website. But when you want to download film, that wasn't made by CT, the app says, that the video is DRM protected.

![screenshot](https://user-images.githubusercontent.com/71781857/159993665-cccd4529-3bed-4fde-818e-af0e9b6d71f6.png)

It would be really nice to have a support for DRM videos.

**Comment by Jeweldation** [comment]
How would that work?

**Comment by Hqmzeh** [comment]
I would like to tell you why this can't work
1) its piracy
2) you need special scripts to decrypt the DRM they add to those videos
which is not available to the public, so putting them in an opensource project will just 
expose the code, and all the members who have access to that script are really specific to whom they give it to

**Comment by pervoj** [comment]
I see.

Ok, I'm closing the issue.
