### ISSUE TITLE
0.2.6: test suite is failing 

### ISSUE THREAD

**Issue by kloczek** [Unrud/video-downloader#14]
```
+ cd video-downloader-0.2.6
+ /usr/bin/meson test -C noarch-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/video-downloader-0.2.6/noarch-redhat-linux-gnu'
ninja: no work to do.
1/3 Validate desktop file   OK             0.07s
2/3 Validate appstream file FAIL           0.99s (exit status 1)
3/3 Validate schema file    OK             0.08s

Ok:                 2
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0


The output from the failed tests:

2/3 Validate appstream file FAIL           0.99s (exit status 1)

--- command ---
01:33:03 /usr/bin/appstream-util validate data/com.github.unrud.VideoDownloader.appdata.xml
--- stdout ---
data/com.github.unrud.VideoDownloader.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> height too small [https://raw.githubusercontent.com/Unrud/video-downloader/0.2.6/screenshots/1.png] minimum is 351px
• attribute-invalid     : <screenshot> height too small [https://raw.githubusercontent.com/Unrud/video-downloader/0.2.6/screenshots/2.png] minimum is 351px
• attribute-invalid     : <screenshot> height too small [https://raw.githubusercontent.com/Unrud/video-downloader/0.2.6/screenshots/3.png] minimum is 351px
• style-invalid         : <ul> cannot start a description [(null)]
• style-invalid         : Not enough <p> tags for a good description [0/1]
--- stderr ---
Validation of files failed
-------

Full log written to /home/tkloczko/rpmbuild/BUILD/video-downloader-0.2.6/noarch-redhat-linux-gnu/meson-logs/testlog.txt
```

**Comment by Unrud** [comment]
The result depends on the version of [appstream-glib](https://github.com/hughsie/appstream-glib). I don't get any errors with version 0.7.16 from [Flathub](https://flathub.org/repo/appstream/org.freedesktop.appstream-glib.flatpakref).

**Comment by kloczek** [comment]
So which one version you are using?

I;m asking because I''m using latest 0.7.17.

**Comment by Unrud** [comment]
> So which one version you are using?

I use the Flathub version (0.7.16). I realized that it is patched with different rules.
To solve the issue I changed the test to use ``validate-relax``.

**Comment by kloczek** [comment]
Yep 0.2.8 is now OK :)

Thank you :)
``+ /usr/bin/meson test -C noarch-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/video-downloader-0.2.8/noarch-redhat-linux-gnu'
ninja: no work to do.
1/3 Validate desktop file   OK             0.06s
2/3 Validate appstream file OK             1.04s
3/3 Validate schema file    OK             0.06s

Ok:                 3
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /home/tkloczko/rpmbuild/BUILD/video-downloader-0.2.8/noarch-redhat-linux-gnu/meson-logs/testlog.txt
```
