### ISSUE TITLE
Feature Request - Allow downloading to removable media

### ISSUE THREAD

**Issue by adam01212** [Unrud/video-downloader#144]
Hey, I can see that you can change the download location in the video-downloader hidden options.....I think that it would be good to have an option in the user interface. Also it would also be great if you could enable the removable-media snap connection so that we could specify a location on removable media.....snap currently does not allow for writing on removable media without the "removable-media" snap connection being made (it can be configured in the BASEDIR/meta/snap.yaml file)

**Comment by Unrud** [comment]
Closed by #152
