### ISSUE TITLE
Exception: You are using an unsupported version of Python.

### ISSUE THREAD

**Issue by jimmychuichui** [Unrud/video-downloader#146]
Exception: You are using an unsupported version of Python. Only Python versions 3.7 and above are supported by yt-dl
<img width="620" alt="Screen Shot 2022-08-16 at 1 21 20 AM" src="https://user-images.githubusercontent.com/60454148/184832782-8e361b95-faf3-4a10-bb59-42e30ddfbf2b.png">

Checked my default python version is 3.9
<img width="261" alt="Screen Shot 2022-08-16 at 1 21 59 AM" src="https://user-images.githubusercontent.com/60454148/184832960-6e4d8c8a-9244-4fc6-a2d3-ce79d84fc476.png">

**Comment by DwarflinDeveloping** [comment]
Have you installed the new version of Ubuntu, 22.04 LTS (Jammy Jellyfish) lately? I have trouble starting some Python applications including this one after the update and get the same error.

**Comment by cavalier32** [comment]
I have the same problem with video-downloader. I get the same "Download failed". I have python version 3.8.10 installed. I am on Kubuntu 22.04.2.0 LTS. I may have removed some necessary dependencies when installing another application. I have also tried re-installing yt-dlp, but that doesn't help.

**Comment by Unrud** [comment]
Caused by https://github.com/Unrud/video-downloader/commit/73ca3b4f8cda1cfcbeae3530e168b3d1f76695ca
I've reverted the stable channel to the previous version. Update snap and it should work again.

**Comment by cavalier32** [comment]
Unrud: Thank you!!!

**Comment by jimmychuichui** [comment]
Thank You!
