### ISSUE TITLE
What yt-dlp commands are used for audio

### ISSUE THREAD

**Issue by sininen-blue** [Unrud/video-downloader#148]
I want to download my playlist even on different machines, and to keep things consistent I'd like to know what string of command you use for yt-dlp

I'm aware that this should be in the source code, but I'm dumb and can't find it

**Comment by Unrud** [comment]
https://github.com/Unrud/video-downloader/blob/1772b3ff4f3a7784bd4394dbcca5cb6e1d620607/src/downloader/yt_dlp_slave.py#L316-L354

**Comment by sininen-blue** [comment]
So I got
`yt-dlp -f 'bestaudio/best[quality=192][acodec=mp3]' -x --audio-format mp3 --embed-thumbnail -o "%(title)s.%(ext)s [link]`

Which I'm not entirely sure if it's correct (should have probably used --postprocessor-args) but it works and the output file is close enough

The only difference is that the files don't have the same sizes, which is weird but it doesn't seem to change much so I'll just ignore it
