### ISSUE TITLE
double quotation mark " in URL bar.

### ISSUE THREAD

**Issue by g6avk** [Unrud/video-downloader#151]
Version - video-downloader-0.10.0

Open Video-downloader and then open a second instance/window from within Video-downloader. 
You will see there is a double quotation mark " in the New window/instance's URL bar.

Note: If I start two separate instances this does not happen and did not with the previous releases. 
This has been reported in MATE and KDE Plasma DE's users on Fedora.

**Comment by tim77** [comment]
This reproducible also with Flathub build.
