### ISSUE TITLE
Welcome page layout

### ISSUE THREAD

**Issue by bertob** [Unrud/video-downloader#154]
This page is a bit boring, some easy fixes:

- Add a statuspage at the top with the app symbolic icon and title like "Download Video"
- Use list rows for the two settings rows
- Make the Download button at the bottom a pill button

![image](https://user-images.githubusercontent.com/1908896/187007210-c50a62c4-643f-4b38-bd05-6beddc91951c.png)

**Comment by Unrud** [comment]
![Screenshot](https://user-images.githubusercontent.com/11810547/187055195-6b3f5600-1645-4592-98b4-c1a17bac9ba3.png)

I'm not sure that's an improvement.

**Comment by bertob** [comment]
> I'm not sure that's an improvement.

Well these are not the recommended widgets, there's AdwListEntry for the entry, and AdwComboRow for the resolution chooser :)

**Comment by Unrud** [comment]
I did not find `AdwListEntry`. I only found `AdwEntryRow`, which is only in beta. `AdwComboRow` looks good.

**Comment by bertob** [comment]
Ah right yeah, I meant entry row. It'll be in 43, which should be out in a few weeks I think.
