### ISSUE TITLE
Application showing incorrectly in English, when the operating system is set to Hungarian

### ISSUE THREAD

**Issue by ovari** [Unrud/video-downloader#165]
![kép](https://user-images.githubusercontent.com/17465872/192125232-128acc2b-e8a4-4681-8138-21d79958a50b.png)

Linux Mint 21 Cinnamon

**Comment by Unrud** [comment]
Can you provide the output:

```
flatpak run --command=sh com.github.unrud.VideoDownloader -c 'env | grep "^\(LANGUAGES\|LC_ALL\|LC_MESSAGES\|LANG\)"'
```

**Comment by ovari** [comment]
```
$ flatpak run --command=sh com.github.unrud.VideoDownloader -c 'env | grep "^\(LANGUAGES\|LC_ALL\|LC_MESSAGES\|LANG\)"'
LANGUAGE=hu_HU
LANG=hu_HU.UTF-8
```

**Comment by ovari** [comment]
Strange, some elements are translated.

![image](https://user-images.githubusercontent.com/17465872/195721880-42a35f3f-5153-4998-a81b-599773022cce.png)

Items which are not translated in the image above are:
1. `Cancel`
2. `Video Downloader`
3. `MB/s` perhaps this need to be added as a string that can be translated?

**Comment by ovari** [comment]
Here, no elements seem to be translated.

![Download finished](https://user-images.githubusercontent.com/17465872/195722124-72957736-2bac-4378-98d1-ce5a899de7c1.png)

**Comment by ovari** [comment]
Could the error be that the [hu.po](../tree/master/po/hu.po) file is incorrect?

Translations are provided by
1. forking this repository
2. translating the strings
3. sending merge request

No special software or commands are used.

**Comment by Unrud** [comment]
Flatpak uses the locale settings to install only required languages. Maybe something went wrong and the language is not installed.

Try:

```
flatpak info com.github.unrud.VideoDownloader.Locale
```

It should report something like:

```
Subdirectories: /hu
```

**Comment by ovari** [comment]
> Flatpak uses the locale settings to install only required languages. Maybe something went wrong and the language is not installed.

If the language is not installed, does it seem strange that a string is translated into Hungarian as shown in the image at https://github.com/Unrud/video-downloader/issues/165#issuecomment-1278242280 ?

> Try:

```
$ flatpak info com.github.unrud.VideoDownloader.Locale
   Azonosító: com.github.unrud.VideoDownloader.Locale
  Hivatkozás: runtime/com.github.unrud.VideoDownloader.Locale/x86_64/stable
Architektúra: x86_64
          Ág: stable
      Eredet: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 62,5 kB

      Kommit: 32609ebf66cbd0586ba8d071e6100194cf21351a90ea27bcbee61100aeded885
       Szülő: b27af2758331138ea642afaceb866b9bd75f48bf841143603a2750a0c06f71f2
       Tárgy: Update to 0.10.8 (7263db1c)
       Dátum: 2022-10-13 22:54:44 +0000
```

> It should report something like:
> 
> `Subdirectories: /hu`

The `subdirectories` or `hu` reference are not shown.

Perhaps there is a regression somewhere as Video Downloader used to show completely in Hungarian?

**Comment by ovari** [comment]
Could code pointers from [Video Trimmer (Videóvágó)](https://flathub.org/apps/details/org.gnome.gitlab.YaLTeR.VideoTrimmer) help as it is shown in Hungarian?

![Video Trimmer (Videóvágó)](https://user-images.githubusercontent.com/17465872/195926736-4d1d4933-c641-4672-843c-2c49f5f6edfd.png)

**Comment by Unrud** [comment]
> The `subdirectories` or `hu` reference are not shown.

I don't know.

Check if the directory exists:

```
flatpak run --command=sh com.github.unrud.VideoDownloader -c 'ls /app/share/runtime/locale/'
```

If the `hu` directory is not displayed, try to install the extension manually:

```
flatpak update --subpath=hu com.github.unrud.VideoDownloader.Locale
```

**Comment by ovari** [comment]
$ flatpak run --command=sh com.github.unrud.VideoDownloader -c 'ls /app/share/runtime/locale/'
ca  cs	de  es	fa  fr	hr  hu	it  ja	nl  pt	ru  sk	sv  tr	uz
```

> If the `hu` directory is not displayed, try to install the extension manually:

Thanks for the command; however, not required as `hu` is displayed.

> If it still doesn't work, check if the runtime language is installed:

```
$ flatpak run --command=sh com.github.unrud.VideoDownloader -c 'ls /usr/share/runtime/locale/'
hu
```

Should the language directories and installed runtime languages be added to the `About` dialog?

Thank you

**Comment by ovari** [comment]
> Check if the directory exists:

```
$ flatpak run --command=sh com.github.unrud.VideoDownloader -c 'ls /app/share/runtime/locale/'
ca  cs	de  es	fa  fr	hr  hu	it  ja	nl  pt	ru  sk	sv  tr	uz
```

> If the `hu` directory is not displayed, try to install the extension manually:

Thanks for the command; however, not required as `hu` is displayed.

> If it still doesn't work, check if the runtime language is installed:

```
$ flatpak run --command=sh com.github.unrud.VideoDownloader -c 'ls /usr/share/runtime/locale/'
hu
```

Should the language directories and installed runtime languages be added to the `About` dialog?

Thank you

**Comment by Unrud** [comment]
Everything seems to be in place, the languages are installed and the environment variables are set.

Try to run the program in the terminal:

```
flatpak run com.github.unrud.VideoDownloader
```

Maybe it displays a useful error message.

**Comment by ovari** [comment]
> Try to run the program in the terminal:
>
> `flatpak run com.github.unrud.VideoDownloader`

No messages show; however, with the latest update Hungarian is showing.

![0.10.9 shows the GUI in magyar (Hungarian)](https://user-images.githubusercontent.com/17465872/196061466-9d012b4c-c5e1-468d-bb6d-720ad5b22fbd.png)

Thank you

**Comment by Unrud** [comment]
> No messages show; however, with the latest update Hungarian is showing.

The update has not changed anything regarding the problem. Does it also work when you start the program from the menu (instead of the terminal)?

**Comment by ovari** [comment]
> Does it also work when you start the program from the menu (instead of the terminal)?

Yes, it shows in Hungarian when opening from the menu.
