### ISSUE TITLE
How about a tick to close Video Downloader once the file downloaded

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#19]
Hi,

How about a tick to close Video Downloader once the file downloaded ?

To keep it simple, I suggest :
- the setting would have the same value accross tabs (audio|video)
- the setting would be kept for the next start

Thanks !

**Comment by Unrud** [comment]
> How about a tick to close Video Downloader once the file downloaded ?

I don't like the idea of cluttering the interface. The program is supposed to be as simple as possible without any unnecessary functions.

**Comment by antistress** [comment]
Ok, I respect the choice.

And what about a tick which would not be in the main GUI but in the "Download finished" box ?

![VideoDownloader_download-finished](https://user-images.githubusercontent.com/2436957/80919358-0133d000-8d59-11ea-8e78-4ddfcf5e2731.png)
