### ISSUE TITLE
unable to download 

### ISSUE THREAD

**Issue by Rpned** [Unrud/video-downloader#194]
ERROR: [youtube] BMMfM3maMkE: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

and other Youtube videos.

Tried to use  https://github.com/yt-dlp/yt-dlp/issues?q= but the issue was tagged invalid

**Comment by vitacell** [comment]
Same here.

**Comment by Rpned** [comment]
I sent the below to notifications@github.com
"I was advised to check yt-dlp version. Used Synaptic Package Manager and found yt-dlp wasn't installed. Installed it and Video Downloader works again.
Cheers"

**Comment by l4wnd4rt** [comment]
Tried all of the above,still not working. Also, updated Brotli [https://www.brotli.org/] using Synaptic.  Getting the same error message as above. Any help would be appreciated! TY!

**Comment by vitacell** [comment]
> Tried all of the above,still not working. Also, updated Brotli [https://www.brotli.org/] using Synaptic. Getting the same error message as above. Any help would be appreciated! TY!

I have video-downloader 0.10.13 + yt-dlp 2023.03.04-1
