### ISSUE TITLE
Playlist downloading from YT works?

### ISSUE THREAD

**Issue by GoodInfoSeeker** [Unrud/video-downloader#2]
I tried playlist downloading few times and it downloads only one video

**Comment by Unrud** [comment]
It should work. Can you give an example URL that doesn't work?

**Comment by GoodInfoSeeker** [comment]
I need to be logged in Youtube, right?
I see it's working now

**Comment by Unrud** [comment]
> I need to be logged in Youtube, right?

It shouldn't be necessary, if the videos are accessible publicly.

**Comment by GoodInfoSeeker** [comment]
Could I somehow send you links that do not work (except here on forum)?

**Comment by Unrud** [comment]
unrud@outlook.com
