### ISSUE TITLE
Authorizing youtube

### ISSUE THREAD

**Issue by Arup65** [Unrud/video-downloader#21]
I downloaded your app from snap store and it works fine except on restricted youtube videos it is unable to download due to authorization issue. Shouldn't there be a pop up asking for credentials.

**Comment by Unrud** [comment]
Detection of private videos was broken in versions < 0.2.7. Check that you have the latest version.
If it still doesn't work please provide an example URL of a video that doesn't work.

**Comment by Arup65** [comment]
Thanks for your prompt reply, my version is latest 02.8 installed from Software Center Ubuntu 20.04

**Comment by Unrud** [comment]
You have to provide an example URL and/or share the error message. I can' t reproduce the issue.

It display a popup asking for credentials for this [private video](https://www.youtube.com/watch?v=tvuXzvnbcdw).

**Comment by Arup65** [comment]
Thanks tried it today and its working fine. Keep up the good work and do
add options to change the save format later if possible.

Regards



Arup
