### ISSUE TITLE
add command-line arguments --audio and --video to start with the corresponding tab preselected

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#22]
Hi,

Following up on issue #13 I would suggest to add 2 command-line arguments : `--audio` would start Video Downloader with the audio tab preselected, and `--video` would start Video Downloader with the video tab preselected.

Thanks

**Comment by Unrud** [comment]
I don't think this is a necessary or particularly useful feature. As a workaround you can just change the preferences before starting a new instance:

```bash
# Set video
flatpak run --command=gsettings com.github.unrud.VideoDownloader set com.github.unrud.VideoDownloader mode video
# Set audio
flatpak run --command=gsettings com.github.unrud.VideoDownloader set com.github.unrud.VideoDownloader mode audio
```

**Comment by antistress** [comment]
Cool, thanks !
