### ISSUE TITLE
Consider a Settings panel for basic user personalization needs

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#23]
First of all, please not that I don't mean to hassle you and that I've well noted your separate answers under issues #5 (reported by someone else) & #19 (reported by myself) and I respect your decisions.

However I wander if, considering both issues, we could imagine something that would suit both.

I mean, it would be strange to create a Settings panel just for one setting.
But, regarding these 2 demands, I wander if you would consider create a Settings panel that would take into account the 2 needs :

- Automatically close Video Downloader once the file is downloaded ON/OFF
- Download folder _____

For an exemple, here is GNOME Web Settings panel (in french) :

![GnomeWebSettingsPanel](https://user-images.githubusercontent.com/2436957/81323442-eaf18100-9084-11ea-829e-de1c78aa61ac.png)

That would allow to keep the GUI straight an simple and also suit some basic user personalization needs

Thanks !

**Comment by Unrud** [comment]
https://github.com/Unrud/video-downloader#hidden-configuration-options

**Comment by antistress** [comment]
I'm not sure that current choice facilitates user experience since it makes options hardly discoverable.

About proposing options to the user :
- Pros : it allows users to reasonably personalize its experience
- Cons : it adds a menu for advanced configuration. Does it add complexity for people that still are happy with default settings ? Not sure !

Thanks

**Comment by Unrud** [comment]
> I'm not sure that current choice facilitates user experience since it makes options hardly discoverable.

Users are not really supposed to discover it. The app is supposed to be minimalistic and just work.
