### ISSUE TITLE
Prioritize H264+AAC over VP9+Opus on YouTube

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#25]
Hi,
Yesterday I wanted to download this movie https://www.youtube.com/watch?v=t7nTMeqwlmE
 to watch it on my TV.
Having chosen the "Best" quality I got a WebM(VP9+Opus) file.
As you may know, H264 is still more common on electronic devices that VP9.
My TV can't handle WebM.
The file I've downloaded was useless for the use case I needed.

Here is the result of the `youtube-dl -F https://www.youtube.com/watch?v=t7nTMeqwlmE` command :

> [youtube] t7nTMeqwlmE: Downloading webpage
> [youtube] t7nTMeqwlmE: Downloading MPD manifest
> [info] Available formats for t7nTMeqwlmE:
> format code  extension  resolution note
> 139          m4a        audio only DASH audio   54k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
> 249          webm       audio only DASH audio   72k , webm_dash container, opus @ 50k (48000Hz)
> 250          webm       audio only DASH audio   90k , webm_dash container, opus @ 70k (48000Hz)
> 140          m4a        audio only DASH audio  102k , m4a_dash container, mp4a.40.2@128k (44100Hz)
> 251          webm       audio only DASH audio  127k , webm_dash container, opus @160k (48000Hz)
> 278          webm       190x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
> 160          mp4        190x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
> 242          webm       318x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
> 133          mp4        318x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
> 243          webm       476x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
> 134          mp4        476x360    DASH video  711k , mp4_dash container, avc1.4d401e, 30fps, video only
> 244          webm       636x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
> 135          mp4        636x480    DASH video 1304k , mp4_dash container, avc1.4d401e, 30fps, video only
> 18           mp4        478x360    360p  408k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 230.45MiB (best)

Then I decided to key `youtube-dl -f 135+140 https://www.youtube.com/watch?v=t7nTMeqwlmE`

Maybe video-downloader should prioritize H264+AAC over VP9+Opus at the same resolution ?

Thanks

**Comment by antistress** [comment]
Same here, for another case : https://www.youtube.com/watch?v=2G73vGWv26E
where I got the 1280 × 720 webm video

```
$ youtube-dl -F https://www.youtube.com/watch?v=AD54fQhSMtw
[youtube] AD54fQhSMtw: Downloading webpage
[info] Available formats for AD54fQhSMtw:
format code  extension  resolution note
249          webm       audio only tiny   53k , opus @ 50k (48000Hz), 14.34MiB
250          webm       audio only tiny   69k , opus @ 70k (48000Hz), 18.61MiB
140          m4a        audio only tiny  132k , m4a_dash container, mp4a.40.2@128k (44100Hz), 38.89MiB
251          webm       audio only tiny  139k , opus @160k (48000Hz), 36.15MiB
278          webm       256x144    144p  109k , webm container, vp9, 25fps, video only, 27.08MiB
160          mp4        256x144    144p  111k , avc1.4d400c, 25fps, video only, 18.41MiB
242          webm       426x240    240p  226k , vp9, 25fps, video only, 46.01MiB
133          mp4        426x240    240p  245k , avc1.4d4015, 25fps, video only, 32.08MiB
243          webm       640x360    360p  412k , vp9, 25fps, video only, 82.07MiB
134          mp4        640x360    360p  633k , avc1.4d401e, 25fps, video only, 75.83MiB
244          webm       854x480    480p  762k , vp9, 25fps, video only, 138.42MiB
135          mp4        854x480    480p 1170k , avc1.4d401e, 25fps, video only, 147.46MiB
247          webm       1280x720   720p 1523k , vp9, 25fps, video only, 277.06MiB
136          mp4        1280x720   720p 2334k , avc1.4d401f, 25fps, video only, 289.97MiB
18           mp4        640x360    360p  488k , avc1.42001E, 25fps, mp4a.40.2@ 96k (44100Hz), 146.61MiB
22           mp4        1280x720   720p 1094k , avc1.64001F, 25fps, mp4a.40.2@192k (44100Hz) (best)
```

**Comment by Unrud** [comment]
https://github.com/Unrud/video-downloader#prefer-mpeg

**Comment by domy-os** [comment]
> https://github.com/Unrud/video-downloader#prefer-mpeg

How to do this for dnf/rpm version?
