### ISSUE TITLE
Suggestion: Option to add numbering from the youtube playlist

### ISSUE THREAD

**Issue by loaderini** [Unrud/video-downloader#26]
This will especially help when the user puts the playlist's url in video-downlader to download the whole playlist with one click only, but the playlist has **too many** videos, which makes manual correction tedious afterwards.

An option to add the numbering that youtube inserts next to the thumbnails when a playlist is created will help when the user wants to download a whole playlist and wants to keep the same video order that already exists in the playlist.

So, instead of downloading _'Example movie review.webm'_ the name of the downloaded file can be _'198 Example movie review.webm'_ if that video's place in the playlist is 198th.

For example, [this playlist](https://www.youtube.com/playlist?list=PLt-jFj7rmphS9OwBkP7kvfA2hxX7tiJCu) has 1051 videos. Youtube automatically created numbering for them, starting from 1 and ending in 1051. If I put the playlist's url in video-downlader it will download all of them, but not in order because there are no numbers in the beggining of each file's name.

Of course, there will be problems with the numbering format for some media players/devices that don't understand that 100 goes after 99 even though 1 goes before 9. It happens when I try to order files in my local router usb storage. But, still, it's better to have some kind of automatic numbering than none at all, especially when a playlist is too large.

**EDIT**: I did it with youtube-dl in terminal. It also automatically created as many zeroes as needed for each file (started with 0001 and ended with 1051). So, maybe this means that this issue doesn't need to be open anymore, you decide. The command I used in youtube-dl is: `youtube-dl -o '/home/Downloads/%(playlist_index)s.%(title)s.%(ext)s' --playlist-reverse --ignore-errors --format best https://www.youtube.com/playlisturl`

**Comment by Unrud** [comment]
> I did it with youtube-dl in terminal.

That's a better choice for use-cases like this. The app is supposed to be minimalistic.
