### ISSUE TITLE
ERROR: ERROR: unable to open for writing: [Errno 36] File name too long:

### ISSUE THREAD

**Issue by Narendran-Kamarajan** [Unrud/video-downloader#28]
While downloading the videos, getting the ERROR: ERROR: unable to open for writing: [Errno 36] File name too long:
It would be helpful to rename the file being downloaded or increase the filename limit.

**Comment by Unrud** [comment]
Can you link to an example?

> or increase the filename limit.

It's a limitation of the OS and file system.

**Comment by Narendran-Kamarajan** [comment]
Thanks for the information, I just confirmed it as the OS limitation on the filename length.
In that case, is it possible to introduce the option to choose the destination filename while downloading? So that if the original filename can be renamed while downloading.
![image](https://user-images.githubusercontent.com/66511020/85202363-84b67a00-b323-11ea-8539-f46b10bc2b16.png)
