### ISSUE TITLE
How to working local clone

### ISSUE THREAD

**Issue by jasurhaydarovcode** [Unrud/video-downloader#294]
Hello i'm download this repo and how to run local, npm i yes and ...

**Comment by mak448a** [comment]
This is a Python project, so you shouldn't use npm. You should be able to open it with Gnome Builder, but I'm not sure how to set it up.

**Comment by Unrud** [comment]
This project doesn't use **npm**. It's build with [meson](https://mesonbuild.com/).
The easiest way to get started is using [Gnome Builder](https://flathub.org/apps/org.gnome.Builder) with Flatpak, because it bundles all the dependencies.
