### ISSUE TITLE
Doesn't work with that particular YouTube playlist

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#30]
Hi,
Usually video-downloader works flawlessly on YouTube, even inside playlists where I got the choice to grab one track or the whole playlist.

For some reason, I couldn't download the audio with video-downloader on any track of that playlist :
https://www.youtube.com/watch?v=SIT-8sjl97c&list=RDSIT-8sjl97c&index=1

Note that it works without the playlist, i.e. : https://www.youtube.com/watch?v=SIT-8sjl97c

I'm using latest Flatpak version.

Thanks

**Comment by Unrud** [comment]
This is a bug in youtube-dl. Please report the issue at https://github.com/ytdl-org/youtube-dl/issues.

**Comment by Unrud** [comment]
I close this here because an issue for youtube-dl exists: https://github.com/ytdl-org/youtube-dl/issues/26228
