### ISSUE TITLE
Bravo, bravo, now the downloader finally doesn't work at all!!!

### ISSUE THREAD

**Issue by heikomandel** [Unrud/video-downloader#308]
After a glorious update, no downloads possible for days!!!
The video is downloaded until shortly before the end, then an error message ‘Encoder not found’ appears and I have a broken download, which only consists of a folder with useless content!
What is this and when will this error finally be fixed?

**Comment by Murray-Dawson** [comment]
Try opening the largest file in that folder - that's working for me, but I get the same assembly error.

**Comment by Unrud** [comment]
Fixed 7774720089e7712cfe85e72b2931f80cd54c2fb4.
