### ISSUE TITLE
Issue with video filenames

### ISSUE THREAD

**Issue by Ahmed-E-86** [Unrud/video-downloader#33]
When I download a playlist, I get the video name + the ID of the video + (247+251) video, and audio quality. How can I turn off all of that?

I just want the video name, and if you can add the number of the video in the playlist before the filename that will be awesome.

**Comment by Unrud** [comment]
> When I download a playlist, I get the video name + the ID of the video + (247+251) video, and audio quality. How can I turn off all of that?

Fixed in eb12092c31bf1051d297363c7404669c081bb21e
