### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [Unrud/video-downloader#36]
The current icon doesn't quite follow the [app icon HIG](https://developer.gnome.org/hig/stable/icon-design.html.en), would you be interested in a new one that's more in line with the platform style?

Here's a quick thing I did, basically just porting the existing icon to the HIG:

![image](https://user-images.githubusercontent.com/1908896/90341897-f64d3480-e003-11ea-8bb2-d054c99a30e0.png)

**Comment by Unrud** [comment]
> would you be interested in a new one that's more in line with the platform style?

Sure.

Related: https://github.com/Unrud/video-downloader/pull/32

> Here's a quick thing I did, basically just porting the existing icon to the HIG:

Looks good.

**Comment by Unrud** [comment]
I've applied the style of your icon to the old icon (523d4c8fe917fb48599b3ab7b2f4e838c78455b5):
![com github unrud VideoDownloader](https://user-images.githubusercontent.com/11810547/91266822-51a0c480-e772-11ea-8d98-eb27bfcc099f.png)

**Comment by bertob** [comment]
I'd avoid the arrow-in-cloud thing (it looks a bit messy), and make the holes on the sides a bit smaller.

Also, I was thinking about ways to make the arrow more interesting, how about this:

![image](https://user-images.githubusercontent.com/1908896/91583702-e0b80300-e951-11ea-99f8-020b287a22e3.png)

**Comment by Unrud** [comment]
> I'd avoid the arrow-in-cloud thing (it looks a bit messy), and make the holes on the sides a bit smaller.

I have no objections.

> Also, I was thinking about ways to make the arrow more interesting

That's definitely an improvement.

**Comment by bertob** [comment]
Cool, I opened a PR with the pixelated arrow one :)
