### ISSUE TITLE
Huge Video and Audio buttons

### ISSUE THREAD

**Issue by Art-2** [Unrud/video-downloader#37]
On no Adwaita themes the buttons for Video and Audio just does not look right:
![Captura de pantalla_2020-08-27_09-50-53](https://user-images.githubusercontent.com/12375357/91466088-df9cae00-e84b-11ea-8eae-4c0320a6b8d1.png)
_Greybird Theme_

Distro: Xubuntu 20.04
Desktop: Xfce 4.14.2
libgtk-3-0: 3.24.20

**Comment by Unrud** [comment]
That's a bit unfortunate but I don't think we can do anything about it.

**Comment by Art-2** [comment]
Does the theme have to be more up to date? 🤔

**Comment by Unrud** [comment]
> Does the theme have to be more up to date?

I don't know if the issue got fixed in newer versions of the theme.

**Comment by Unrud** [comment]
I close this issue because it's a problem of the Greybird theme.
