### ISSUE TITLE
flatpak video-downloader doesn't start anymore

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#39]
$ flatpak run com.github.unrud.VideoDownloader
Unable to init server: Impossible de se connecter : Connexion refusée
Unable to init server: Impossible de se connecter : Connexion refusée
Unable to init server: Impossible de se connecter : Connexion refusée

(video-downloader:3): Gtk-WARNING **: 22:00:34.259: cannot open display: 

$ flatpak run com.github.unrud.VideoDownloader -v
Unable to init server: Impossible de se connecter : Connexion refusée
Unable to init server: Impossible de se connecter : Connexion refusée
Option inconnue -v

FWIW no pb with i.e $ flatpak run org.audacityteam.Audacity
and $ flatpak run org.audacityteam.Audacity -v

Note that GTK runtime has been updated recently and an old one has been removed.

Here is an extract of $ flatpak list
Name                                    Application ID                                      Version    Branch Origin        Installation
Video Downloader                        com.github.unrud.VideoDownloader                    0.4.1      stable flathub       system
Codecs                                  org.audacityteam.Audacity.Codecs                               stable flathub       system
Freedesktop Platform                    org.freedesktop.Platform                            19.08.12   19.08  flathub       system
default                                 org.freedesktop.Platform.GL.default                            19.08  flathub       system
Intel                                   org.freedesktop.Platform.VAAPI.Intel                           19.08  flathub       system
openh264                                org.freedesktop.Platform.openh264                   2.1.0      2.0    flathub       system
GNOME Application Platform version 3.36 org.gnome.Platform                                             3.36   flathub       system
KDE Application Platform                org.kde.Platform                                               5.14   flathub       system
QGnomePlatform                          org.kde.PlatformTheme.QGnomePlatform                           5.14   flathub       system
QtSNI                                   org.kde.PlatformTheme.QtSNI                                    5.14   flathub       system
QGnomePlatform-decoration               org.kde.WaylandDecoration.QGnomePlatform-decoration            5.14   flathub       system

Thanks

**Comment by Unrud** [comment]
Have you used Wayland? Try to restart the computer.

**Comment by antistress** [comment]
Hi,
You're right
For whatever reason my session switched back to X11
Back to Wayland video-downloader runs again
Thanks
