### ISSUE TITLE
Support For Downloading Subtitles

### ISSUE THREAD

**Issue by dlalinsp** [Unrud/video-downloader#40]
There's currently no option for downloading subtitles (when available) in Video Downloader. I currently have to use youtube-dl as well just to download the subtitles for some videos. It would be cool if this was added too.

**Comment by Unrud** [comment]
Available subtitles are now embedded into videos.

**Comment by JaneSmith** [comment]
I came here to request this feature and found this issue... I must be confused about how it's supposed to work, as literally none of my downloads appear to have subtitles. Does this only work on videos with "official" subtitles?

I want to download the auto-generated subtitles that YouTube generates. All of the videos I've tried have these auto-generated subtitles, which I can see when I watch them on YouTube. After downloading with Video Downloader, I open the video in Celluloid and there are no subtitle tracks available.

**Comment by Unrud** [comment]
Auto-generated subtitles are not included.

**Comment by JaneSmith** [comment]
If that could be added as a feature, I'd certainly find it very helpful! For myself, I'd only need to download the auto-generated subtitles in one language.

I'm currently trying to do it manually by copying and pasting the transcript from YouTube into a text file and then converting that to subtitle format, but it's a lot of work. Not so bad for a single video, but impractical to do a large number of videos.

**Comment by JaneSmith** [comment]
Thanks a lot for implementing this. I've been using it and it helps a lot.

I've noticed that sometimes I don't get the full subtitles with longer videos, but I believe that's bug 30049 in `youtube-dl` itself, so it'll be fixed on their side at some point.

Thanks again!

**Comment by Unrud** [comment]
> I've noticed that sometimes I don't get the full subtitles with longer videos

Please provide a link to an example video? The video mentioned in https://github.com/ytdl-org/youtube-dl/issues/30049 works fine with the latest version.
