### ISSUE TITLE
Allow Multiple Downloads

### ISSUE THREAD

**Issue by dlalinsp** [Unrud/video-downloader#42]
For those who want to download multiple videos simultaneously, this is an issue with Video Downloader. I currently have to open multiple windows and manage it manually. It could useful to let the user add/remove multiple URL fields and Video Downloader can download the videos one-by-one.

**Comment by Unrud** [comment]
> I currently have to open multiple windows and manage it manually.

That's the intended usage.

> It could useful to let the user add/remove multiple URL fields and Video Downloader can download the videos one-by-one.

Yes, but I try to keep the program as simple as possible.

**Comment by dlalinsp** [comment]
> > I currently have to open multiple windows and manage it manually.
> 
> That's the intended usage.
> 
> > It could useful to let the user add/remove multiple URL fields and Video Downloader can download the videos one-by-one.
> 
> Yes, but I try to keep the program as simple as possible.

I respect that. However, it might be a better idea to make it more apparent to the user by adding a button to open a new window directly from the application. I recommend placing a 'plus' sign on the top-left corner of the window. (Something like in Celluloid.)
