### ISSUE TITLE
video downloader now donwloads the whole YouTube playlist without asking

### ISSUE THREAD

**Issue by antistress** [Unrud/video-downloader#43]
Hi,
With latest Flatpak, I've experienced that video downloader now donwloads the whole YouTube playlist without asking
(i.e. with https://www.youtube.com/playlist?list=PL-gd_cQDUsQebAeHBZcWoTknRcS3YsMy6)
That wasn't the case before.
Don't know if it's a bug or a new feature (cant find the changelist)
Thanks

**Comment by Unrud** [comment]
> With latest Flatpak, I've experienced that video downloader now donwloads the whole YouTube playlist without asking

The behaviour did not change. It only asks if the website contains a single video **and** a playlist.

Try:

https://www.youtube.com/watch?v=cJebuPrUs6E&list=PL-gd_cQDUsQebAeHBZcWoTknRcS3YsMy6&index=2&t=0s

**Comment by antistress** [comment]
You're right. That's excellent.
Sorry for the noise
Cheers
