### ISSUE TITLE
There Are Issues When Downloading Some Videos As Audio Files

### ISSUE THREAD

**Issue by dlalinsp** [Unrud/video-downloader#46]
I was trying to download this video on YouTube *as an audio file*: https://www.youtube.com/watch?v=zFhfksjf_mY. However, Video Downloader gets stuck after a while.  I tried this several times but it did not work. When I tried to download it as a *video*, it worked fine.

**Comment by Unrud** [comment]
> However, Video Downloader gets stuck after a while.

You have to wait. It takes some time to convert the file to MP3 because it's over an hour long.
The progress bar is not moving because youtube-dl doesn't give any feedback during the operation.

**Comment by dlalinsp** [comment]
>  It takes some time to convert the file to MP3 because it's over an hour long.
Why doesn't it happen when I download it as a video, though?

**Comment by Unrud** [comment]
> Why doesn't it happen when I download it as a video, though?

It's not feasible to convert videos. It would take forever.

Fixed in https://github.com/Unrud/video-downloader/commit/62dae3d67ed79b36fbd0a3e63d5289038ec66256
