### ISSUE TITLE
Allow changing the download directory

### ISSUE THREAD

**Issue by pizzadude** [Unrud/video-downloader#5]
Hi, nice program. :)
It would be cool if we could change the download directory.
A workaround is to symlink somewhere else to ~/Downloads/VideoDownloader, but this is not ideal.
Thanks for making this cool front-end for youtube-dl!

**Comment by Unrud** [comment]
This would interfere with the sandbox. The Flatpak version only allows access to the ``~/Downloads/VideoDownloader`` directory.

I could add an environment variable to change the directory. For users that manually changed the permissions of the sandbox to allow access to a different directory.

**Comment by Unrud** [comment]
The download folder can be configured in GSettings: https://github.com/Unrud/video-downloader/blob/942d7f92b95c68b2d872e0d2a55786edbfe1c4e6/data/com.github.unrud.VideoDownloader.gschema.xml#L9

**Comment by pizzadude** [comment]
@Unrud how do I set it? I tried:
`gsettings set com.github.unrud.VideoDownloader download-folder /path/to/download/folder
No such schema “com.github.unrud.VideoDownloader”
`
I'm on Fedora KDE

**Comment by Unrud** [comment]
Flatpak:
```bash
flatpak run --command=gsettings com.github.unrud.VideoDownloader set com.github.unrud.VideoDownloader download-folder /path/to/download/folder
```

Snap:
```bash
gsettings --schemadir /snap/video-downloader/current/usr/share/glib-2.0/schemas set com.github.unrud.VideoDownloader download-folder /path/to/download/folder
```
