### ISSUE TITLE
Video or audio not being downloaded.

### ISSUE THREAD

**Issue by rajib-raiyat** [Unrud/video-downloader#50]
version: 0.5.8 (latest) (on date 2020-10-19)
device: pc 
os: linux

**My YouTube URL is a publicly accessible URL but it still says ...**

ERROR: n8LUQGOe1Ks: YouTube said: Unable to extract video data

**Comment by Unrud** [comment]
It works for me. I've tested the Flatpak and Snap version.

**Comment by rajib-raiyat** [comment]
So why isn't it working properly for me?

**Comment by rajib-raiyat** [comment]
@Unrud  My link[](https://www.youtube.com/playlist?list=PLoo7iQEJfCdACXrX4stFnXfHy3vLFOagk) is a link to a song playlist on YouTube. And this link is publicly accessacble. 

And I want all the songs in that playlist to be downloaded as mp3.
