### ISSUE TITLE
Persian/Farsi Translation.

### ISSUE THREAD

**Issue by AliKhomami** [Unrud/video-downloader#52]
Hello,
I'd like to translate your great app in Persian/Farsi which is mainly spoken in countries like Iran, Tajikistan, & Afghanistan.

But the problem is I don't know how I can exactly do that!

Peace & blessings be upon you!

**Comment by Unrud** [comment]
You have to create a *.po file for the language. They are located in the [./po](https://github.com/Unrud/video-downloader/tree/master/po) folder.

Probably the easiest way is too use a tool like Poedit ([Flatpak](https://flathub.org/apps/details/net.poedit.Poedit) / [Snap](https://snapcraft.io/poedit)). Create a new translation and use one of the already existing *.po files as a template.

**Comment by AliKhomami** [comment]
Thanks for your reply!
