### ISSUE TITLE
Change code for non-copyrighted vídeos/music only

### ISSUE THREAD

**Issue by GustavoPeredo** [Unrud/video-downloader#57]
Recently the project youtube-dl and all its forks have been taken down by a DMCA request (copyright infringment), I really like this project and am worried that they could take down/open a process against the developer(s).

Apparently the problem was because youtube-dl circumvented youtube's copyright protection, so, if you could change the code to remove such functionality, your project won't have the chance of being taken down.

**Comment by Unrud** [comment]
> if you could change the code to remove such functionality

youtube-dl is an external dependency of this project. The code is not part of this project.

**Comment by GustavoPeredo** [comment]
Thank you for your explanation
