### ISSUE TITLE
[Feature request] add batch download list

### ISSUE THREAD

**Issue by prog-amateur2** [Unrud/video-downloader#6]
Hello, I think you know the excellent [youtube-dl-gui](https://github.com/MrS0m30n3/youtube-dl-gui). It works well but seems to have been abandoned by its author (to be confirmed). I really like your design which respects the Linux interface. 

But the main advantage between youtube-dl-gui and video-downloader, is that it allows you to download a list of contents, so there is no need to repeat the operation.  

Could you please implement such a feature? 

Thank you

**Comment by Unrud** [comment]
I would rather keep it simple.
I myself just start multiple instances of the applications to download a list of videos.

**Comment by prog-amateur2** [comment]
It's a point of view. I have tested to open multiple instances and I could do it, so I close this issue as you prefer to not have a common monitor. 
Thank you for your feedback.
