### ISSUE TITLE
Nicer "download finished" view

### ISSUE THREAD

**Issue by bertob** [Unrud/video-downloader#72]
This view looks a bit off-style, I'd recommend

- using a centered layout, where icon, title, and text are below one another
- using a symbolic icon and making it larger (e.g. 64 or 96px). The light bulb icon also doesn't make sense here, I'd use something success- or download-related, e.g. `document-save-symbolic`
- using a larger font size for the title (I'd recommend looking at the GTK text style classes)
- on the back button, using a regular back button icon rather than a "back" label. Alternatively you could also drop the back button and have a centered "New Download" button below everything else

![image](https://user-images.githubusercontent.com/1908896/104206211-8d8dab00-542f-11eb-93cf-9614c37906cd.png)

**Comment by GustavoPeredo** [comment]
@bertob Is this similar to what you have in mind?
![Captura de tela de 2021-01-11 15-30-45](https://user-images.githubusercontent.com/30641461/104223499-77c5b900-5422-11eb-967d-1cbd8609ad12.png)

**Comment by bertob** [comment]
Much better!

I'd increase the spacing above and below the label to about 3x the current value (maybe 24 or 30px), otherwise it looks good to me.

**Comment by GustavoPeredo** [comment]
I think I can implement that, do you agree with the changes @Unrud ?

**Comment by Unrud** [comment]
Looks okay but I would like to keep the title "Download finished". Something like "Open Download Location" would be more descriptive for the button and the icon in the button seems unnecessary.

**Comment by GustavoPeredo** [comment]
Great, I'll be working on that :)

**Comment by GustavoPeredo** [comment]
I know that the issue is targeted at the download view, but I think that we could have a redesign on the error page as well.

Current design:
![Screenshot from 2021-01-12 19-45-02](https://user-images.githubusercontent.com/30641461/104383521-b9339280-550e-11eb-939c-f49c18fc92c9.png)

Design suggestion (with only one of the symbols ofc):
![Screenshot from 2021-01-12 19-44-42](https://user-images.githubusercontent.com/30641461/104383560-c9e40880-550e-11eb-9b38-6316e9853949.png)

What do you think?

**Comment by Unrud** [comment]
> What do you think?

Looks good to me.

**Comment by GustavoPeredo** [comment]
Implemented!

PS: Undur, if you want me to solve any other issues, just tag me on them ;). I really like this app, so it's a pleasure to contribute to it

**Comment by GustavoPeredo** [comment]
GIF comparing the new design

![sem título](https://user-images.githubusercontent.com/30641461/106372190-1a9b9400-634c-11eb-8ebc-a1ae47c39076.GIF)
