### ISSUE TITLE
Where is the default save directory?

### ISSUE THREAD

**Issue by myhecks** [Unrud/video-downloader#81]

**Comment by GustavoPeredo** [comment]
Your home folder > Downloads > VideoDownloader (~/Downloads/VideoDownloader/)

**Comment by mbnoimi** [comment]
> Your home folder > Downloads > VideoDownloader (~/Downloads/VideoDownloader/)

This doesn't work!; The app shows me `~/VideoDownloader/` as a destination path, but it doesn't exist!
Is there any way to set the download path?

**Comment by GustavoPeredo** [comment]
Yes there is a way to set a download page, go to the main page of this project ([here](https://github.com/Unrud/video-downloader)) and scroll to the very bottom (there is also an option to prefer mpeg)

**Comment by mbnoimi** [comment]
> Yes there is a way to set a download page, go to the main page of this project (here) and scroll to the very bottom (there is also an option to prefer mpeg)

Are you kidding me!? This is the first thing I did. Any way; I fixed the problem by replacing `~` with full path of user home.

**Comment by flxzt** [comment]
Is there a reason not to expose this in the UI? It would not even need to have a settings menu, it could just be a entry displaying the current folder and a button for a filechooser to set a new one located below the colorschemes

**Comment by Unrud** [comment]
Closed by #152
