### ISSUE TITLE
Clicking On Notification Doesn't Work!

### ISSUE THREAD

**Issue by ProfessorCode212** [Unrud/video-downloader#92]
Since the last release, Video Downloader shows a notification whenever it finishes downloading a video. However, clicking on the _Open Download Location_ button in the notification message doesn't work. I am on Linux Mint 19.3 Cinnamon Edition.

**Comment by Unrud** [comment]
For some reason the parameter for the actions are not returned to the program. (Clicking on the notification also should bring the window to the foreground.) Probably some incompatibility with the old version of Linux Mint, maybe try a newer version.
